on:
  push:
    tags:
      - 'v*' # Push events to a tag matching v*, i.e. v1.0, v20.15.10

name: Release

jobs:
  publish-to-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          registry-url: 'https://registry.npmjs.org/'
          scope: 'expo'
          node-version: 20
      - name: Setup ncc
        run: npm install -g @vercel/ncc
      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files
      - name: Build
        run: yarn build
      - name: Publish packages to npm
        run: yarn lerna publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  open-pr-in-turtle-v2:
    name: Open a PR with version bumps in turtle-v2
    needs: publish-to-npm
    runs-on: ubuntu-latest
    steps:
      - name: Open a PR with version bumps in turtle-v2
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: expo/turtle-v2
          ref: main
          workflow: update-eas-build-modules.yml
          token: ${{ secrets.EXPO_BOT_PAT }}
  open-pr-in-eas-cli:
    name: Open a PR with version bumps in eas-cli
    needs: publish-to-npm
    runs-on: ubuntu-latest
    steps:
      - name: Open a PR with version bumps in eas-cli
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: expo/eas-cli
          ref: main
          workflow: upgrade-eas-build-modules.yml
          token: ${{ secrets.EXPO_BOT_PAT }}
