name: Run tests
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20", "22"]
    name: Test with Node ${{ matrix.node }} on Linux
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: Setup ncc
        run: npm install -g @vercel/ncc
      - run: yarn install --frozen-lockfile --check-files
      - name: "gql.tada Checks"
        working-directory: packages/build-tools
        run: |
          yarn gql
          yarn gql-tada check
          git diff --name-status --exit-code .
      - run: yarn build
      - run: yarn test
      - run: yarn lint --max-warnings=0
